spring:
  # 애플리케이션 이름
  application:
    name: loan-manager-api

  # 환경에 따라 프로파일 설정
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  #  show-sql: true: 실행되는 SQL 쿼리를 콘솔에 출력
  #  format_sql: true: SQL 쿼리를 보기 좋게 포맷팅
  #  highlight_sql: true: SQL 쿼리에 하이라이트 적용
  #  use_sql_comments: true: JPQL 주석도 함께 출력
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        highlight_sql: true


---


# local 프로파일 설정
spring:
  config:
    activate:
      on-profile: local

  # PostgreSQL 연결 설정
  datasource:
    url: jdbc:postgresql://${DB_URL:loan-db}:${DB_PORT:5432}/${DB_NAME:mydb}
    username: ${DB_USERNAME:loan-user}
    password: ${DB_PASSWORD:loan-1234}
    driver-class-name: org.postgresql.Driver
  
  # 개발 도구 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


---

# test 프로파일 설정
spring:
  config:
    activate:
      on-profile: dev
  
  # 테스트 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  # h2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console  



---


# prod 프로파일 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


---


# 공통 설정
spring:
  # application.oauth.yml 파일을 포함
  profiles:
    include:
      - oauth

  # Redis 설정 (Spring Boot 3.x 버전)
  data:
    redis:
      host: ${REDIS_HOST:redis-server}
      port: ${REDIS_PORT:6379}

# JWT Configuration
jwt:
  secret: growtogether123456789012345678901234567890
  expiration-seconds: 86400
  refresh-token-validity-in-milliseconds: 604800000

# Logging Configuration
logging:
  #file:
  #  name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com:  
      gt: DEBUG
    org:
      springframework:
        web: INFO
        hibernate: debug
        SQL: debug
      hibernate:
        #SQL: debug
        type:
          descriptor:
            sql: TRACE
