spring:
  application:
    name: GTPlatform
  
  profiles:
    include:
      - oauth
  
  # PostgreSQL 연결 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/gt-platform
    username: gt-user
    password: gt-1234
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  # Security OAuth2 설정
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  # Redis 설정 (Spring Boot 3.x 버전)
  data:
    redis:
      host: localhost
      port: 6379    

#      password: # 필요한 경우
#      database: 0 # Redis 데이터베이스 인덱스 (0-15)
#      timeout: 60000 # 연결 타임아웃 (ms)
#      lettuce:
#        pool:
#          max-active: 8 # 풀의 최대 연결 수
#          max-idle: 8 # 풀의 최대 유휴 연결 수
#          min-idle: 0 # 풀의 최소 유휴 연결 수
#          max-wait: -1 # 풀이 바쁠 때 연결을 기다리는 최대 시간 (-1은 무제한)


# JWT Configuration
jwt:
  secret: growtogether123456789012345678901234567890
  expiration-seconds: 86400
  refresh-token-validity-in-milliseconds: 604800000

# OAuth2 관련 추가 설정
app:
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect
    success-url: http://localhost:3000/oauth2/success
    failure-url: http://localhost:3000/oauth2/failure

# Logging Configuration
logging:
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.gt: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO  