name: PR Pipeline

on:
 pull_request:
   branches: 
     - main

jobs:
  pull_request_build_test:
    runs-on: ubuntu-latest    
    steps:
    - 
      name: Checkout Repository
      uses: actions/checkout@v4  
      # 현재 리포지토리를 체크아웃합니다.

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      # 다중 플랫폼(Docker) 이미지를 빌드할 수 있도록 해준다.

    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  
      # Docker Buildx를 설정합니다.

    - 
      name: Build and Push
      uses: docker/build-push-action@v2
      with:
        # 빌드 컨텍스트 : Dockerfile이 있는 위치
        context: .
        # Dockerfile의 경로
        file: Dockerfile
        build-args: |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
        push: false
        platforms: linux/amd64,linux/arm64,linux/arm/v7
  
  create-issue-on-failure:
    needs: pull_request_build_test
    if: failure() # 빌드 실패 시 실행
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          echo $G_TOKEN | gh auth login --with-token

      - name: Create Issue for Build Failure
        run: |
          gh issue create --title "Build Failure in PR #${{ github.event.pull_request.number }}" \
                          --body "The build for PR #${{ github.event.pull_request.html_url }} failed. Please investigate." \
                          --label "bug,build-failure"  
